//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlackSchedule.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SlackSchedule.App_LocalResources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   © {0} - HPB Quản lý lịch làm việc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string appCopyright {
            get {
                return ResourceManager.GetString("appCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lịch làm việc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thêm mới に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Xóa に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lưu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ~/Scripts/datatables/Vietnamese.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string datatables_Lang {
            get {
                return ResourceManager.GetString("datatables_Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trang chủ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_PageTitle {
            get {
                return ResourceManager.GetString("home_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] [{1}] {2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_task_GlobalContent {
            get {
                return ResourceManager.GetString("home_task_GlobalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{0}] {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_task_PrivateContent {
            get {
                return ResourceManager.GetString("home_task_PrivateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tất cả task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_title_GlobalTask {
            get {
                return ResourceManager.GetString("home_title_GlobalTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task cá nhân に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_title_PrivateTask {
            get {
                return ResourceManager.GetString("home_title_PrivateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task hôm nay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_title_TodayTask {
            get {
                return ResourceManager.GetString("home_title_TodayTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task trễ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string home_title_UncompleteTask {
            get {
                return ResourceManager.GetString("home_title_UncompleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string list_Action {
            get {
                return ResourceManager.GetString("list_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_Active {
            get {
                return ResourceManager.GetString("member_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thông tin member に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_EditTitle {
            get {
                return ResourceManager.GetString("member_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_Email {
            get {
                return ResourceManager.GetString("member_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Danh sách member に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_ListTitle {
            get {
                return ResourceManager.GetString("member_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Họ tên に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_Name {
            get {
                return ResourceManager.GetString("member_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mật khẩu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_Password {
            get {
                return ResourceManager.GetString("member_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Slack ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string member_SlackID {
            get {
                return ResourceManager.GetString("member_SlackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trang chủ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_Home {
            get {
                return ResourceManager.GetString("menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quản lý に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_Management {
            get {
                return ResourceManager.GetString("menu_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thành viên に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_Member {
            get {
                return ResourceManager.GetString("menu_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ngày nghỉ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_OffDate {
            get {
                return ResourceManager.GetString("menu_OffDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cấu hình văn phòng に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_OfficeSetting {
            get {
                return ResourceManager.GetString("menu_OfficeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menu_Project {
            get {
                return ResourceManager.GetString("menu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Khách hàng に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_CustomerName {
            get {
                return ResourceManager.GetString("project_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thông tin dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_EditTitle {
            get {
                return ResourceManager.GetString("project_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Danh sách dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ListTitle {
            get {
                return ResourceManager.GetString("project_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectCoder {
            get {
                return ResourceManager.GetString("project_ProjectCoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thời gian に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectDate {
            get {
                return ResourceManager.GetString("project_ProjectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ngày end に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectEnd {
            get {
                return ResourceManager.GetString("project_ProjectEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hoàn thành に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectFinish {
            get {
                return ResourceManager.GetString("project_ProjectFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectLeader {
            get {
                return ResourceManager.GetString("project_ProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tên dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectName {
            get {
                return ResourceManager.GetString("project_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ngày start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectStart {
            get {
                return ResourceManager.GetString("project_ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tình trạng に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectState {
            get {
                return ResourceManager.GetString("project_ProjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tester に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string project_ProjectTester {
            get {
                return ResourceManager.GetString("project_ProjectTester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Người&lt;br/&gt;phụ trách に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_Curator {
            get {
                return ResourceManager.GetString("schedule_Curator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Leader に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_Leader {
            get {
                return ResourceManager.GetString("schedule_Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lịch dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_PageTitle {
            get {
                return ResourceManager.GetString("schedule_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thời gian phát triển に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_ProjectDate {
            get {
                return ResourceManager.GetString("schedule_ProjectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dự án に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_ProjectName {
            get {
                return ResourceManager.GetString("schedule_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_Task {
            get {
                return ResourceManager.GetString("schedule_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskEnd {
            get {
                return ResourceManager.GetString("schedule_TaskEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Estimated&lt;br/&gt;Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskEstimateTime {
            get {
                return ResourceManager.GetString("schedule_TaskEstimateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Finish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskFinish {
            get {
                return ResourceManager.GetString("schedule_TaskFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Real&lt;br/&gt;Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskRealTime {
            get {
                return ResourceManager.GetString("schedule_TaskRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskStart {
            get {
                return ResourceManager.GetString("schedule_TaskStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tình trạng に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string schedule_TaskState {
            get {
                return ResourceManager.GetString("schedule_TaskState", resourceCulture);
            }
        }
    }
}
